name: Deploy to Agile On PR Merge
# 12344
on:
    pull_request:
      types: 
        [closed]

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a test command
              run: echo "This is a test job"                  